src = ["chanx", "tests"]
target-version = "py310"

[lint]
ignore = [
  "B009",  # we need to use getattr in some special case
  "E501",  # line too long, handled by black
  "F405",  # defined from star imports
  "PLR0913"  # Too many arguments in function definition
]
select = [
  "B",  # flake8-bugbear
  "C",  # flake8-comprehensions
  "E",  # pycodestyle errors
  "F",  # pyflakes
  "I",  # isort
  "N",  # pep8-naming
  "PL",  # pylint
  "Q",  # flake8-quotes
  "UP",  # pyupgrade
  "W"  # pycodestyle warnings
]

[lint.isort]
section-order = ["future", "standard-library", "django", "third-party", "first-party", "local-folder"]

[lint.isort.sections]
django = ["channels", "django", "rest_framework"]

[lint.per-file-ignores]
"chanx/asyncapi/type_defs.py" = ["C901", "N815", "PLR0912"]
"chanx/client_generator/analyzer.py" = ["C901", "PLR0912"]
"chanx/client_generator/codegen.py" = ["C901", "PLR0911", "PLR0912"]
"ext/*" = ["PLR2004"]
"sandbox_*/*/test_*.py" = ["B009", "C901", "N806", "PLR0911", "PLR2004"]
"tests/*" = ["B009", "C901", "N806", "PLR0911", "PLR2004"]
